### ISSUE TITLE
__getstate__ method returns a traits_version key

### ISSUE THREAD

**Issue by martinRenou** [force-h2020/force-bdss#63] opened 2017-07-31 15:15 UTC
When writing a JSON file, the `__getstate__` method returns a traits_version entry, which is written in the  JSON file. This can be useful when dealing with incompatibility between trait version used when writing the file and trait version used when reading the file.

Now, when reading the file, the traits_version is added to the model of the currently created entity (MCO, data source or KPI calculator). But this traits_version wasn't part of the model when writing the file. This results, in the UI, in an editable entry `traits version` when selecting the model.

We should deal with the traits_version in the Workflow reader: raise an issue if the traits_version is not compatible; and remove the traits_version from the model.

**Comment by stefanoborini** [comment] 2018-06-20 15:26
Duplicate of #134

**Closed by stefanoborini** 2018-06-20 15:26 UTC
